name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: {% raw %}${{ secrets.HF_TOKEN }}{% endraw %}
        run: git push https://{{cookiecutter.repo_owner}}:$HF_TOKEN@huggingface.co/spaces/{{cookiecutter.namespace}} main